name: Test
on: [ push ]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java-version: [ 17, 21 ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v7

            -   name: Setup Java
                uses: actions/setup-java@v6
                with:
                    distribution: zulu
                    java-version: ${{ matrix.java-version }}
                    architecture: x64
                    cache: maven

            -   name: Maven Test
                run: mvn --batch-mode test
